repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: local
    hooks:
    -   id: java-format
        name: Java Format
        description: Format Java code using google-java-format
        entry: just -f jlox/justfile format
        language: system
        types: [java]
        pass_filenames: false
